.class public final Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;
.super Ljava/lang/Object;
.source "BlobRepositoryModel.kt"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "Blob"
.end annotation

.annotation runtime Lkotlin/Metadata;
    bv = {
        0x1,
        0x0,
        0x3
    }
    d1 = {
        "\u00002\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u000b\n\u0002\u0008\u0002\n\u0002\u0010\u0008\n\u0002\u0008\u0002\n\u0002\u0010\u000e\n\u0002\u0008\r\n\u0002\u0010\t\n\u0002\u0008\u0016\n\u0002\u0018\u0002\n\u0002\u0008\u000b\u0018\u00002\u00020\u0001B\u0011\u0008\u0000\u0012\u0006\u0010/\u001a\u00020.\u00a2\u0006\u0004\u00087\u00108J\u001a\u0010\u0004\u001a\u00020\u00032\u0008\u0010\u0002\u001a\u0004\u0018\u00010\u0001H\u0096\u0002\u00a2\u0006\u0004\u0008\u0004\u0010\u0005J\u000f\u0010\u0007\u001a\u00020\u0006H\u0016\u00a2\u0006\u0004\u0008\u0007\u0010\u0008R\u0015\u0010\u000c\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\n\u0010\u000bR\u0015\u0010\u000e\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\r\u0010\u000bR\u0015\u0010\u0010\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\u000f\u0010\u000bR\u0015\u0010\u0012\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\u0011\u0010\u000bR\u0015\u0010\u0014\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\u0013\u0010\u000bR\u0015\u0010\u0016\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\u0015\u0010\u000bR\u0015\u0010\u001a\u001a\u0004\u0018\u00010\u00178F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\u0018\u0010\u0019R\u0015\u0010\u001c\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\u001b\u0010\u000bR\u0015\u0010\u001e\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\u001d\u0010\u000bR\u0015\u0010 \u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008\u001f\u0010\u000bR\u0015\u0010\"\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008!\u0010\u000bR\u0015\u0010%\u001a\u0004\u0018\u00010\u00038F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008#\u0010$R\u0015\u0010\'\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008&\u0010\u000bR\u0015\u0010)\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008(\u0010\u000bR\u0015\u0010+\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008*\u0010\u000bR\u0015\u0010-\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u0008,\u0010\u000bR\u0016\u0010/\u001a\u00020.8\u0002@\u0002X\u0082\u0004\u00a2\u0006\u0006\n\u0004\u0008/\u00100R\u0015\u00102\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u00081\u0010\u000bR\u0015\u00104\u001a\u0004\u0018\u00010\u00038F@\u0006\u00a2\u0006\u0006\u001a\u0004\u00083\u0010$R\u0015\u00106\u001a\u0004\u0018\u00010\t8F@\u0006\u00a2\u0006\u0006\u001a\u0004\u00085\u0010\u000b\u00a8\u00069"
    }
    d2 = {
        "Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;",
        "",
        "other",
        "",
        "equals",
        "(Ljava/lang/Object;)Z",
        "",
        "hashCode",
        "()I",
        "",
        "getDataAccessUrlExpiry",
        "()Ljava/lang/String;",
        "dataAccessUrlExpiry",
        "getBucket",
        "bucket",
        "getBlobPath",
        "blobPath",
        "getManagingOrganization",
        "managingOrganization",
        "getAttachmentUrl",
        "attachmentUrl",
        "getCreation",
        "creation",
        "",
        "getAttachmentSize",
        "()Ljava/lang/Long;",
        "attachmentSize",
        "getGuid",
        "guid",
        "getAttachmentCreation",
        "attachmentCreation",
        "getDataAccessUrl",
        "dataAccessUrl",
        "getDataType",
        "dataType",
        "getAutoGeneratedBlobPathName",
        "()Ljava/lang/Boolean;",
        "autoGeneratedBlobPathName",
        "getBlobName",
        "blobName",
        "getLastUpdated",
        "lastUpdated",
        "getCreatedBy",
        "createdBy",
        "getPropositionGuid",
        "propositionGuid",
        "Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;",
        "blob",
        "Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;",
        "getState",
        "state",
        "getUploadedOnBehalf",
        "uploadedOnBehalf",
        "getVersionId",
        "versionId",
        "<init>",
        "(Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;)V",
        "connectivity-hsdp-client_release"
    }
    k = 0x1
    mv = {
        0x1,
        0x4,
        0x2
    }
.end annotation


# instance fields
.field private final blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;


# direct methods
.method public constructor <init>(Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;)V
    .locals 1

    const-string v0, "blob"

    invoke-static {p1, v0}, Ln/l0/d/r;->e(Ljava/lang/Object;Ljava/lang/String;)V

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    iput-object p1, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    return-void
.end method


# virtual methods
.method public equals(Ljava/lang/Object;)Z
    .locals 3

    const/4 v0, 0x1

    if-ne p0, p1, :cond_0

    return v0

    :cond_0
    if-eqz p1, :cond_2

    .line 1
    const-class v1, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;

    invoke-static {v1}, Ln/l0/d/h0;->b(Ljava/lang/Class;)Ln/q0/d;

    move-result-object v1

    invoke-virtual {p1}, Ljava/lang/Object;->getClass()Ljava/lang/Class;

    move-result-object v2

    invoke-static {v2}, Ln/l0/d/h0;->b(Ljava/lang/Class;)Ln/q0/d;

    move-result-object v2

    invoke-static {v1, v2}, Ln/l0/d/r;->a(Ljava/lang/Object;Ljava/lang/Object;)Z

    move-result v1

    xor-int/2addr v0, v1

    if-eqz v0, :cond_1

    goto :goto_0

    .line 2
    :cond_1
    check-cast p1, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;

    .line 3
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    iget-object p1, p1, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-static {v0, p1}, Ln/l0/d/r;->a(Ljava/lang/Object;Ljava/lang/Object;)Z

    move-result p1

    return p1

    :cond_2
    :goto_0
    const/4 p1, 0x0

    return p1
.end method

.method public final getAttachmentCreation()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getAttachment()Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Attachment;

    move-result-object v0

    if-eqz v0, :cond_0

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Attachment;->getCreation()Ljava/lang/String;

    move-result-object v0

    goto :goto_0

    :cond_0
    const/4 v0, 0x0

    :goto_0
    return-object v0
.end method

.method public final getAttachmentSize()Ljava/lang/Long;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getAttachment()Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Attachment;

    move-result-object v0

    if-eqz v0, :cond_0

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Attachment;->getSize()Ljava/lang/Long;

    move-result-object v0

    goto :goto_0

    :cond_0
    const/4 v0, 0x0

    :goto_0
    return-object v0
.end method

.method public final getAttachmentUrl()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getAttachment()Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Attachment;

    move-result-object v0

    if-eqz v0, :cond_0

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Attachment;->getUrl()Ljava/lang/String;

    move-result-object v0

    goto :goto_0

    :cond_0
    const/4 v0, 0x0

    :goto_0
    return-object v0
.end method

.method public final getAutoGeneratedBlobPathName()Ljava/lang/Boolean;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getAutoGenerateBlobPathName()Ljava/lang/Boolean;

    move-result-object v0

    return-object v0
.end method

.method public final getBlobName()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getBlobName()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getBlobPath()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getBlobPath()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getBucket()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getBucket()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getCreatedBy()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getCreatedBy()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getCreation()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getCreation()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getDataAccessUrl()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getDataAccessUrl()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getDataAccessUrlExpiry()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getDataAccessUrlExpiry()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getDataType()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getDataType()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getGuid()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getGuid()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getLastUpdated()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getMeta()Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Meta;

    move-result-object v0

    if-eqz v0, :cond_0

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Meta;->getLastUpdated()Ljava/lang/String;

    move-result-object v0

    goto :goto_0

    :cond_0
    const/4 v0, 0x0

    :goto_0
    return-object v0
.end method

.method public final getManagingOrganization()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getManagingOrganization()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getPropositionGuid()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getPropositionGuid()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public final getState()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getState()Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob$State;

    move-result-object v0

    if-eqz v0, :cond_0

    invoke-virtual {v0}, Ljava/lang/Enum;->name()Ljava/lang/String;

    move-result-object v0

    goto :goto_0

    :cond_0
    const/4 v0, 0x0

    :goto_0
    return-object v0
.end method

.method public final getUploadedOnBehalf()Ljava/lang/Boolean;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getUploadOnBehalf()Ljava/lang/Boolean;

    move-result-object v0

    return-object v0
.end method

.method public final getVersionId()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->getMeta()Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Meta;

    move-result-object v0

    if-eqz v0, :cond_0

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Meta;->getVersionId()Ljava/lang/String;

    move-result-object v0

    goto :goto_0

    :cond_0
    const/4 v0, 0x0

    :goto_0
    return-object v0
.end method

.method public hashCode()I
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/philips/connectivity/hsdpclient/api/model/BlobRepositoryModel$Blob;->blob:Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;

    invoke-virtual {v0}, Lcom/philips/connectivity/hsdpclient/generated/models/blobrepository/v1/Blob;->hashCode()I

    move-result v0

    return v0
.end method
